import { User } from '../models/user.model';
import { Recipe } from '../models/recipe.model';
import { Ingredient } from '../models/ingredient.model';
import { Comment } from '../models/comment.model';
import { Subscription } from '../models/subscription.model';
import { Rating } from '../models/rating.model';

// ─── Mock User ────────────────────────────────────────────────────────────────

export const MOCK_USER: User = {
  id: 'user-001',
  email: 'alice@soapmaker.com',
  displayName: 'Alice Brewer',
  avatarUrl: 'https://i.pravatar.cc/150?img=47',
  bio: 'Passionate soap maker since 2018. I love cold-process and experimenting with natural colorants.',
  isPremium: false,
  isInTrial: true,
  trialStartedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  trialEndsAt: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
  trialDaysRemaining: 5,
  dateJoined: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
};

// ─── Mock Ingredients ─────────────────────────────────────────────────────────

export const MOCK_INGREDIENTS: Ingredient[] = [
  { id: 'i-01', name: 'Coconut Oil', category: 'oil', saponificationValue: 0.190, description: 'Hard oil, adds lather and hardness.' },
  { id: 'i-02', name: 'Olive Oil', category: 'oil', saponificationValue: 0.134, description: 'Skin-conditioning oil, mild lather.' },
  { id: 'i-03', name: 'Palm Oil', category: 'oil', saponificationValue: 0.141, description: 'Adds hardness and stable lather.' },
  { id: 'i-04', name: 'Castor Oil', category: 'oil', saponificationValue: 0.128, description: 'Boosts lather and adds creaminess.' },
  { id: 'i-05', name: 'Sweet Almond Oil', category: 'oil', saponificationValue: 0.136, description: 'Lightweight skin softener.' },
  { id: 'i-06', name: 'Shea Butter', category: 'oil', saponificationValue: 0.128, description: 'Rich butter for moisturising bars.' },
  { id: 'i-07', name: 'Cocoa Butter', category: 'oil', saponificationValue: 0.137, description: 'Hard butter with faint chocolate scent.' },
  { id: 'i-08', name: 'Avocado Oil', category: 'oil', saponificationValue: 0.133, description: 'Nourishing oil for sensitive skin.' },
  { id: 'i-09', name: 'Sunflower Oil', category: 'oil', saponificationValue: 0.134, description: 'Light conditioning oil.' },
  { id: 'i-10', name: 'Hemp Seed Oil', category: 'oil', saponificationValue: 0.135, description: 'Anti-inflammatory, great for dry skin.' },
  { id: 'i-11', name: 'Jojoba Oil', category: 'oil', saponificationValue: 0.069, description: 'Actually a wax ester; very conditioning.' },
  { id: 'i-12', name: 'Argan Oil', category: 'oil', saponificationValue: 0.136, description: 'Luxurious conditioning Moroccan oil.' },
  { id: 'i-13', name: 'Sodium Hydroxide (NaOH)', category: 'lye', saponificationValue: null, description: 'Caustic soda for cold/hot process.' },
  { id: 'i-14', name: 'Potassium Hydroxide (KOH)', category: 'lye', saponificationValue: null, description: 'Lye for liquid soap.' },
  { id: 'i-15', name: 'Distilled Water', category: 'liquid', saponificationValue: null, description: 'Standard soap-making liquid.' },
  { id: 'i-16', name: 'Goat Milk', category: 'liquid', saponificationValue: null, description: 'Adds creaminess and skin-loving lactic acid.' },
  { id: 'i-17', name: 'Coconut Milk', category: 'liquid', saponificationValue: null, description: 'Fluffy lather and tropical scent.' },
  { id: 'i-18', name: 'Lavender Essential Oil', category: 'fragrance', saponificationValue: null, description: 'Calming floral scent.' },
  { id: 'i-19', name: 'Peppermint Essential Oil', category: 'fragrance', saponificationValue: null, description: 'Fresh, cooling aroma.' },
  { id: 'i-20', name: 'Rose Clay', category: 'colorant', saponificationValue: null, description: 'Natural pink colorant with mild detoxifying properties.' },
];

// ─── Mock Recipes ─────────────────────────────────────────────────────────────

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r-01', slug: 'lavender-dream',
    name: 'Lavender Dream',
    description: 'A classic cold-process soap infused with lavender essential oil and topped with dried lavender buds. Perfect for gifting.',
    method: 'cold_process', difficulty: 'beginner',
    cureTimeDays: 28, batchSizeGrams: 500, yieldBars: 8,
    imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400',
    isPublished: true,
    tags: [{ id: 't-1', name: 'lavender' }, { id: 't-2', name: 'floral' }],
    ingredients: [
      { ingredient: MOCK_INGREDIENTS[0], amountGrams: 200, percentage: 40, notes: '' },
      { ingredient: MOCK_INGREDIENTS[1], amountGrams: 150, percentage: 30, notes: 'Extra-virgin preferred' },
      { ingredient: MOCK_INGREDIENTS[2], amountGrams: 100, percentage: 20, notes: '' },
      { ingredient: MOCK_INGREDIENTS[3], amountGrams: 50, percentage: 10, notes: 'Boosts bubbles' },
    ],
    steps: [
      { id: 's1', order: 1, instruction: 'Prepare your workspace and weigh all oils.', durationMinutes: 10 },
      { id: 's2', order: 2, instruction: 'Mix lye into water slowly; allow to cool to 40°C.', durationMinutes: 20 },
      { id: 's3', order: 3, instruction: 'Combine oils and lye solution; stick-blend to light trace.', durationMinutes: 5 },
      { id: 's4', order: 4, instruction: 'Add lavender EO, stir, pour into mould. Insulate for 24 hours.', durationMinutes: 5 },
    ],
    averageRating: 4.8, ratingCount: 124,
    authorId: 'user-001', authorName: 'Alice Brewer', authorAvatar: 'https://i.pravatar.cc/40?img=47',
    createdAt: '2024-01-10T10:00:00Z', updatedAt: '2024-02-01T12:00:00Z',
  },
  {
    id: 'r-02', slug: 'citrus-burst',
    name: 'Citrus Burst',
    description: 'Zesty and energising — a lemon-orange swirl soap made with fresh citrus zest and a touch of turmeric for colour.',
    method: 'cold_process', difficulty: 'intermediate',
    cureTimeDays: 35, batchSizeGrams: 600, yieldBars: 10,
    imageUrl: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400',
    isPublished: true,
    tags: [{ id: 't-3', name: 'citrus' }, { id: 't-4', name: 'energising' }],
    ingredients: [
      { ingredient: MOCK_INGREDIENTS[0], amountGrams: 240, percentage: 40, notes: '' },
      { ingredient: MOCK_INGREDIENTS[1], amountGrams: 180, percentage: 30, notes: '' },
      { ingredient: MOCK_INGREDIENTS[5], amountGrams: 60, percentage: 10, notes: 'Adds moisture' },
      { ingredient: MOCK_INGREDIENTS[3], amountGrams: 60, percentage: 10, notes: '' },
    ],
    steps: [
      { id: 's1', order: 1, instruction: 'Weigh and melt hard oils. Let cool to 38°C.', durationMinutes: 15 },
      { id: 's2', order: 2, instruction: 'Prepare lye solution with water. Cool to 38°C.', durationMinutes: 20 },
      { id: 's3', order: 3, instruction: 'Blend oils and lye to light trace. Split into two bowls.', durationMinutes: 5 },
      { id: 's4', order: 4, instruction: 'Add lemon EO to one half, orange to other. Pour swirl pattern.', durationMinutes: 10 },
    ],
    averageRating: 4.5, ratingCount: 89,
    authorId: 'user-001', authorName: 'Alice Brewer', authorAvatar: 'https://i.pravatar.cc/40?img=47',
    createdAt: '2024-01-20T10:00:00Z', updatedAt: '2024-02-05T12:00:00Z',
  },
  {
    id: 'r-03', slug: 'charcoal-detox',
    name: 'Charcoal Detox',
    description: 'Deep-cleansing activated charcoal bar with tea tree oil. Great for oily skin and removing impurities.',
    method: 'cold_process', difficulty: 'beginner',
    cureTimeDays: 28, batchSizeGrams: 500, yieldBars: 8,
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400',
    isPublished: true,
    tags: [{ id: 't-5', name: 'charcoal' }, { id: 't-6', name: 'detox' }],
    ingredients: [
      { ingredient: MOCK_INGREDIENTS[0], amountGrams: 200, percentage: 40, notes: '' },
      { ingredient: MOCK_INGREDIENTS[8], amountGrams: 150, percentage: 30, notes: '' },
      { ingredient: MOCK_INGREDIENTS[2], amountGrams: 100, percentage: 20, notes: '' },
    ],
    steps: [
      { id: 's1', order: 1, instruction: 'Mix activated charcoal into a small amount of oil to disperse.', durationMinutes: 5 },
      { id: 's2', order: 2, instruction: 'Make lye solution, cool. Combine with oils at trace.', durationMinutes: 25 },
      { id: 's3', order: 3, instruction: 'Add charcoal mixture and tea tree EO. Pour and cure.', durationMinutes: 5 },
    ],
    averageRating: 4.7, ratingCount: 203,
    authorId: 'user-002', authorName: 'Bob Crafts', authorAvatar: 'https://i.pravatar.cc/40?img=12',
    createdAt: '2024-01-15T10:00:00Z', updatedAt: '2024-02-10T12:00:00Z',
  },
  {
    id: 'r-04', slug: 'goat-milk-honey',
    name: 'Goat Milk & Honey',
    description: 'Ultra-moisturising bar with goat milk and raw honey. Great for dry and sensitive skin.',
    method: 'cold_process', difficulty: 'intermediate',
    cureTimeDays: 42, batchSizeGrams: 700, yieldBars: 12,
    imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400',
    isPublished: true,
    tags: [{ id: 't-7', name: 'sensitive' }, { id: 't-8', name: 'moisturising' }],
    ingredients: [
      { ingredient: MOCK_INGREDIENTS[1], amountGrams: 280, percentage: 40, notes: '' },
      { ingredient: MOCK_INGREDIENTS[0], amountGrams: 210, percentage: 30, notes: '' },
      { ingredient: MOCK_INGREDIENTS[5], amountGrams: 140, percentage: 20, notes: '' },
    ],
    steps: [
      { id: 's1', order: 1, instruction: 'Freeze goat milk partially. Slowly add lye to prevent scorching.', durationMinutes: 20 },
      { id: 's2', order: 2, instruction: 'Melt and cool oils. Combine at light trace.', durationMinutes: 15 },
      { id: 's3', order: 3, instruction: 'Add honey at medium trace. Pour into moulds.', durationMinutes: 5 },
    ],
    averageRating: 4.9, ratingCount: 312,
    authorId: 'user-003', authorName: 'Carol Makes', authorAvatar: 'https://i.pravatar.cc/40?img=23',
    createdAt: '2024-02-01T10:00:00Z', updatedAt: '2024-02-15T12:00:00Z',
  },
  {
    id: 'r-05', slug: 'peppermint-shampoo-bar',
    name: 'Peppermint Shampoo Bar',
    description: 'A high-lather shampoo bar with peppermint for a tingly, refreshing scalp experience.',
    method: 'hot_process', difficulty: 'advanced',
    cureTimeDays: 14, batchSizeGrams: 400, yieldBars: 6,
    imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400',
    isPublished: true,
    tags: [{ id: 't-9', name: 'shampoo' }, { id: 't-10', name: 'peppermint' }],
    ingredients: [
      { ingredient: MOCK_INGREDIENTS[0], amountGrams: 200, percentage: 50, notes: '' },
      { ingredient: MOCK_INGREDIENTS[3], amountGrams: 80, percentage: 20, notes: '' },
    ],
    steps: [
      { id: 's1', order: 1, instruction: 'Make lye solution. Combine with oils and cook in slow cooker.', durationMinutes: 60 },
      { id: 's2', order: 2, instruction: 'Cook until applesauce stage, add peppermint EO off-heat.', durationMinutes: 5 },
    ],
    averageRating: 4.3, ratingCount: 67,
    authorId: 'user-002', authorName: 'Bob Crafts', authorAvatar: 'https://i.pravatar.cc/40?img=12',
    createdAt: '2024-02-05T10:00:00Z', updatedAt: '2024-02-20T12:00:00Z',
  },
  {
    id: 'r-06', slug: 'rose-clay-facial',
    name: 'Rose Clay Facial Bar',
    description: 'Gentle facial soap with rose clay for a soft pink hue and rose absolute for a romantic scent.',
    method: 'cold_process', difficulty: 'beginner',
    cureTimeDays: 28, batchSizeGrams: 500, yieldBars: 8,
    imageUrl: 'https://images.unsplash.com/photo-1607008829749-c0f284a49fc4?w=400',
    isPublished: true,
    tags: [{ id: 't-11', name: 'facial' }, { id: 't-2', name: 'floral' }],
    ingredients: [
      { ingredient: MOCK_INGREDIENTS[1], amountGrams: 200, percentage: 40, notes: '' },
      { ingredient: MOCK_INGREDIENTS[4], amountGrams: 100, percentage: 20, notes: '' },
      { ingredient: MOCK_INGREDIENTS[10], amountGrams: 50, percentage: 10, notes: 'Add at trace' },
    ],
    steps: [
      { id: 's1', order: 1, instruction: 'Mix rose clay in a little oil. Weigh remaining oils.', durationMinutes: 10 },
      { id: 's2', order: 2, instruction: 'Saponify at room temperature. Add clay mixture at trace.', durationMinutes: 15 },
    ],
    averageRating: 4.6, ratingCount: 88,
    authorId: 'user-003', authorName: 'Carol Makes', authorAvatar: 'https://i.pravatar.cc/40?img=23',
    createdAt: '2024-02-10T10:00:00Z', updatedAt: '2024-02-25T12:00:00Z',
  },
  {
    id: 'r-07', slug: 'eucalyptus-mint',
    name: 'Eucalyptus & Mint',
    description: 'A spa-inspired bar combining eucalyptus and spearmint essential oils for a clean, invigorating wash.',
    method: 'melt_and_pour', difficulty: 'beginner',
    cureTimeDays: 7, batchSizeGrams: 300, yieldBars: 6,
    imageUrl: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f1a1?w=400',
    isPublished: true,
    tags: [{ id: 't-12', name: 'eucalyptus' }, { id: 't-13', name: 'spa' }],
    ingredients: [],
    steps: [
      { id: 's1', order: 1, instruction: 'Melt M&P base in microwave in 30-second bursts.', durationMinutes: 5 },
      { id: 's2', order: 2, instruction: 'Add EOs and colour, pour into moulds. Spritz with alcohol.', durationMinutes: 5 },
    ],
    averageRating: 4.1, ratingCount: 42,
    authorId: 'user-001', authorName: 'Alice Brewer', authorAvatar: 'https://i.pravatar.cc/40?img=47',
    createdAt: '2024-02-15T10:00:00Z', updatedAt: '2024-03-01T12:00:00Z',
  },
  {
    id: 'r-08', slug: 'oat-and-honey-gentle',
    name: 'Oat & Honey Gentle Bar',
    description: 'Colloidal oatmeal and manuka honey make this the softest, most soothing bar for sensitive and eczema-prone skin.',
    method: 'cold_process', difficulty: 'beginner',
    cureTimeDays: 28, batchSizeGrams: 550, yieldBars: 9,
    imageUrl: 'https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=400',
    isPublished: true,
    tags: [{ id: 't-7', name: 'sensitive' }, { id: 't-14', name: 'oat' }],
    ingredients: [],
    steps: [],
    averageRating: 4.95, ratingCount: 450,
    authorId: 'user-003', authorName: 'Carol Makes', authorAvatar: 'https://i.pravatar.cc/40?img=23',
    createdAt: '2024-02-20T10:00:00Z', updatedAt: '2024-03-05T12:00:00Z',
  },
  {
    id: 'r-09', slug: 'coffee-scrub-bar',
    name: 'Coffee Scrub Bar',
    description: 'Coarsely-ground coffee beans embedded in a coconut oil base. Brilliant for exfoliation and cellulite massage.',
    method: 'cold_process', difficulty: 'beginner',
    cureTimeDays: 28, batchSizeGrams: 500, yieldBars: 8,
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=400',
    isPublished: true,
    tags: [{ id: 't-15', name: 'exfoliating' }, { id: 't-16', name: 'coffee' }],
    ingredients: [],
    steps: [],
    averageRating: 4.4, ratingCount: 178,
    authorId: 'user-002', authorName: 'Bob Crafts', authorAvatar: 'https://i.pravatar.cc/40?img=12',
    createdAt: '2024-03-01T10:00:00Z', updatedAt: '2024-03-10T12:00:00Z',
  },
  {
    id: 'r-10', slug: 'sea-salt-spa-bar',
    name: 'Sea Salt Spa Bar',
    description: 'High-salt bar (80% salt ratio) that creates a creamy, lotion-like lather and leaves skin silky smooth.',
    method: 'cold_process', difficulty: 'advanced',
    cureTimeDays: 14, batchSizeGrams: 600, yieldBars: 10,
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400',
    isPublished: true,
    tags: [{ id: 't-13', name: 'spa' }, { id: 't-17', name: 'sea-salt' }],
    ingredients: [],
    steps: [],
    averageRating: 4.2, ratingCount: 95,
    authorId: 'user-001', authorName: 'Alice Brewer', authorAvatar: 'https://i.pravatar.cc/40?img=47',
    createdAt: '2024-03-05T10:00:00Z', updatedAt: '2024-03-15T12:00:00Z',
  },
  {
    id: 'r-11', slug: 'turmeric-glow',
    name: 'Turmeric Glow Bar',
    description: 'Turmeric-infused soap with black seed oil and a hint of orange EO for a golden, brightening bar.',
    method: 'cold_process', difficulty: 'intermediate',
    cureTimeDays: 35, batchSizeGrams: 500, yieldBars: 8,
    imageUrl: 'https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=400',
    isPublished: true,
    tags: [{ id: 't-18', name: 'brightening' }, { id: 't-3', name: 'citrus' }],
    ingredients: [],
    steps: [],
    averageRating: 4.6, ratingCount: 134,
    authorId: 'user-003', authorName: 'Carol Makes', authorAvatar: 'https://i.pravatar.cc/40?img=23',
    createdAt: '2024-03-10T10:00:00Z', updatedAt: '2024-03-20T12:00:00Z',
  },
  {
    id: 'r-12', slug: 'beer-soap-ipa',
    name: 'IPA Beer Soap',
    description: 'Craft beer replaces water in this man-cave favourite. The hops and sugars create a rich, stable lather.',
    method: 'hot_process', difficulty: 'advanced',
    cureTimeDays: 14, batchSizeGrams: 700, yieldBars: 12,
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
    isPublished: true,
    tags: [{ id: 't-19', name: 'beer' }, { id: 't-20', name: 'masculine' }],
    ingredients: [],
    steps: [],
    averageRating: 3.9, ratingCount: 56,
    authorId: 'user-002', authorName: 'Bob Crafts', authorAvatar: 'https://i.pravatar.cc/40?img=12',
    createdAt: '2024-03-15T10:00:00Z', updatedAt: '2024-03-25T12:00:00Z',
  },
];

// ─── Mock Comments ────────────────────────────────────────────────────────────

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c-01',
    parent: null,
    body: 'This lavender bar turned out beautifully! The scent is perfect — not too strong. I cured mine for 5 weeks and it is rock-hard.',
    authorName: 'Sarah L.',
    authorAvatar: 'https://i.pravatar.cc/40?img=5',
    isFlagged: false,
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    replies: [
      {
        id: 'c-01a',
        parent: 'c-01',
        body: 'Agreed! I added a little bit of lavender buds on top and it looks gorgeous.',
        authorName: 'Mike R.',
        authorAvatar: 'https://i.pravatar.cc/40?img=11',
        isFlagged: false,
        createdAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
        replies: [],
      },
    ],
  },
  {
    id: 'c-02',
    parent: null,
    body: 'What superfat percentage do you recommend for a beginner-friendly version of this recipe?',
    authorName: 'Jenny K.',
    authorAvatar: 'https://i.pravatar.cc/40?img=9',
    isFlagged: false,
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    replies: [
      {
        id: 'c-02a',
        parent: 'c-02',
        body: 'I always go 5-7% for cold process. 5% makes a harder bar, 7% is more skin-nourishing.',
        authorName: 'Alice Brewer',
        authorAvatar: 'https://i.pravatar.cc/40?img=47',
        isFlagged: false,
        createdAt: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
        replies: [],
      },
    ],
  },
  {
    id: 'c-03',
    parent: null,
    body: 'Made this three times now. Each time better than the last. The goat milk version is my favourite!',
    authorName: 'Tom F.',
    authorAvatar: 'https://i.pravatar.cc/40?img=15',
    isFlagged: false,
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'c-04',
    parent: null,
    body: 'Any tips on achieving a nice top design? Mine always looks a bit lumpy when I pour.',
    authorName: 'Emma W.',
    authorAvatar: 'https://i.pravatar.cc/40?img=20',
    isFlagged: false,
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    replies: [],
  },
  {
    id: 'c-05',
    parent: null,
    body: 'Just discovered this community — incredible recipes here. Already ordered my ingredients for the charcoal bar!',
    authorName: 'Priya S.',
    authorAvatar: 'https://i.pravatar.cc/40?img=32',
    isFlagged: false,
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    replies: [],
  },
];

// ─── Mock Subscription ────────────────────────────────────────────────────────

export const MOCK_SUBSCRIPTION: Subscription = {
  id: 'sub-001',
  plan: 'premium_monthly',
  status: 'trialing',
  currentPeriodEnd: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
  cancelAtPeriodEnd: false,
};

// ─── Mock Ratings ─────────────────────────────────────────────────────────────

export const MOCK_RATING: Rating = {
  id: 'rat-001',
  stars: 5,
  createdAt: new Date().toISOString(),
};
